[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-embed = "8" #嵌入文件
sqlx = { version = "0.8", features = ["runtime-async-std", "sqlite", "macros"] }
sqlparser = "0.61"
syn = { version = "2", features = ["full", "extra-traits", "parsing", "visit"] }
prettyplease = "0.2" #代码格式化
mime_guess = "2"
chrono = "0.4"
regex = "1"
serde = { version = "1", features = ["derive","rc"] }